[2024-11-23T16:42:58.581+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T16:42:58.598+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: interpark_to_s3.extract scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-23T16:42:58.609+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: interpark_to_s3.extract scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-23T16:42:58.609+0000] {taskinstance.py:2866} INFO - Starting attempt 12 of 12
[2024-11-23T16:42:58.630+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): extract> on 2024-11-21 00:00:00+00:00
[2024-11-23T16:42:58.636+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T16:42:58.638+0000] {standard_task_runner.py:72} INFO - Started process 79 to run task
[2024-11-23T16:42:58.639+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'interpark_to_s3', 'extract', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpvluzatx8']
[2024-11-23T16:42:58.640+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask extract
[2024-11-23T16:42:58.694+0000] {task_command.py:467} INFO - Running <TaskInstance: interpark_to_s3.extract scheduled__2024-11-21T00:00:00+00:00 [running]> on host c886796f7651
[2024-11-23T16:42:58.792+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='interpark_to_s3' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-23T16:42:58.793+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T16:42:58.833+0000] {baseoperator.py:416} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-11-23T16:42:58.835+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv6ip7ocnh --python=python
[2024-11-23T16:42:58.836+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T16:43:00.334+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 654ms
[2024-11-23T16:43:00.334+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv6ip7ocnh, clear=False, no_vcs_ignore=False, global=False)
[2024-11-23T16:43:00.335+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-23T16:43:00.336+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2024-11-23T16:43:00.336+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-23T16:43:00.374+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv6ip7ocnh/bin/pip install -r /tmp/venv6ip7ocnh/requirements.txt
[2024-11-23T16:43:00.375+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T16:43:02.214+0000] {process_utils.py:194} INFO - Collecting git+https://github.com/hahahellooo/interpark.git@0.3/new_crawling (from -r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:02.215+0000] {process_utils.py:194} INFO -   Cloning https://github.com/hahahellooo/interpark.git (to revision 0.3/new_crawling) to /tmp/pip-req-build-bqrxlfpr
[2024-11-23T16:43:02.232+0000] {process_utils.py:194} INFO -   Running command git clone --filter=blob:none --quiet https://github.com/hahahellooo/interpark.git /tmp/pip-req-build-bqrxlfpr
[2024-11-23T16:43:03.756+0000] {process_utils.py:194} INFO -   Running command git checkout -b 0.3/new_crawling --track origin/0.3/new_crawling
[2024-11-23T16:43:04.380+0000] {process_utils.py:194} INFO -   Switched to a new branch '0.3/new_crawling'
[2024-11-23T16:43:04.381+0000] {process_utils.py:194} INFO -   branch '0.3/new_crawling' set up to track 'origin/0.3/new_crawling'.
[2024-11-23T16:43:04.381+0000] {process_utils.py:194} INFO -   Resolved https://github.com/hahahellooo/interpark.git to commit d2ab75a632be9f578ac04be0e85d884befd10f87
[2024-11-23T16:43:04.387+0000] {process_utils.py:194} INFO -   Installing build dependencies: started
[2024-11-23T16:43:08.610+0000] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2024-11-23T16:43:08.611+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2024-11-23T16:43:09.539+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'done'
[2024-11-23T16:43:09.541+0000] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): started
[2024-11-23T16:43:10.343+0000] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): finished with status 'done'
[2024-11-23T16:43:10.558+0000] {process_utils.py:194} INFO - Collecting selenium>=4.26.1 (from interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:10.624+0000] {process_utils.py:194} INFO -   Downloading selenium-4.26.1-py3-none-any.whl.metadata (7.1 kB)
[2024-11-23T16:43:10.709+0000] {process_utils.py:194} INFO - Collecting beautifulsoup4>=4.12.3 (from interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:10.717+0000] {process_utils.py:194} INFO -   Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
[2024-11-23T16:43:10.806+0000] {process_utils.py:194} INFO - Collecting soupsieve>1.2 (from beautifulsoup4>=4.12.3->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:10.813+0000] {process_utils.py:194} INFO -   Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
[2024-11-23T16:43:10.943+0000] {process_utils.py:194} INFO - Collecting urllib3<3,>=1.26 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:10.951+0000] {process_utils.py:194} INFO -   Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
[2024-11-23T16:43:11.064+0000] {process_utils.py:194} INFO - Collecting trio~=0.17 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.072+0000] {process_utils.py:194} INFO -   Downloading trio-0.27.0-py3-none-any.whl.metadata (8.6 kB)
[2024-11-23T16:43:11.168+0000] {process_utils.py:194} INFO - Collecting trio-websocket~=0.9 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.175+0000] {process_utils.py:194} INFO -   Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
[2024-11-23T16:43:11.269+0000] {process_utils.py:194} INFO - Collecting certifi>=2021.10.8 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.276+0000] {process_utils.py:194} INFO -   Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
[2024-11-23T16:43:11.373+0000] {process_utils.py:194} INFO - Collecting typing_extensions~=4.9 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.381+0000] {process_utils.py:194} INFO -   Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
[2024-11-23T16:43:11.491+0000] {process_utils.py:194} INFO - Collecting websocket-client~=1.8 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.501+0000] {process_utils.py:194} INFO -   Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
[2024-11-23T16:43:11.606+0000] {process_utils.py:194} INFO - Collecting attrs>=23.2.0 (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.616+0000] {process_utils.py:194} INFO -   Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
[2024-11-23T16:43:11.788+0000] {process_utils.py:194} INFO - Collecting sortedcontainers (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.796+0000] {process_utils.py:194} INFO -   Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
[2024-11-23T16:43:11.928+0000] {process_utils.py:194} INFO - Collecting idna (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:11.937+0000] {process_utils.py:194} INFO -   Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
[2024-11-23T16:43:12.023+0000] {process_utils.py:194} INFO - Collecting outcome (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:12.033+0000] {process_utils.py:194} INFO -   Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
[2024-11-23T16:43:12.158+0000] {process_utils.py:194} INFO - Collecting sniffio>=1.3.0 (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:12.160+0000] {process_utils.py:194} INFO -   Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
[2024-11-23T16:43:12.206+0000] {process_utils.py:194} INFO - Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:12.216+0000] {process_utils.py:194} INFO -   Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
[2024-11-23T16:43:12.319+0000] {process_utils.py:194} INFO - Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:12.333+0000] {process_utils.py:194} INFO -   Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
[2024-11-23T16:43:12.415+0000] {process_utils.py:194} INFO - Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venv6ip7ocnh/requirements.txt (line 1))
[2024-11-23T16:43:12.424+0000] {process_utils.py:194} INFO -   Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
[2024-11-23T16:43:12.477+0000] {process_utils.py:194} INFO - Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
[2024-11-23T16:43:12.531+0000] {process_utils.py:194} INFO - Downloading selenium-4.26.1-py3-none-any.whl (9.7 MB)
[2024-11-23T16:43:14.946+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 4.0 MB/s eta 0:00:00
[2024-11-23T16:43:14.954+0000] {process_utils.py:194} INFO - Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
[2024-11-23T16:43:15.013+0000] {process_utils.py:194} INFO - Using cached soupsieve-2.6-py3-none-any.whl (36 kB)
[2024-11-23T16:43:15.036+0000] {process_utils.py:194} INFO - Downloading trio-0.27.0-py3-none-any.whl (481 kB)
[2024-11-23T16:43:15.157+0000] {process_utils.py:194} INFO - Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
[2024-11-23T16:43:15.188+0000] {process_utils.py:194} INFO - Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
[2024-11-23T16:43:15.253+0000] {process_utils.py:194} INFO - Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
[2024-11-23T16:43:15.305+0000] {process_utils.py:194} INFO - Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
[2024-11-23T16:43:15.367+0000] {process_utils.py:194} INFO - Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
[2024-11-23T16:43:15.403+0000] {process_utils.py:194} INFO - Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
[2024-11-23T16:43:15.451+0000] {process_utils.py:194} INFO - Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
[2024-11-23T16:43:15.507+0000] {process_utils.py:194} INFO - Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
[2024-11-23T16:43:15.557+0000] {process_utils.py:194} INFO - Downloading idna-3.10-py3-none-any.whl (70 kB)
[2024-11-23T16:43:15.601+0000] {process_utils.py:194} INFO - Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
[2024-11-23T16:43:15.648+0000] {process_utils.py:194} INFO - Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
[2024-11-23T16:43:15.701+0000] {process_utils.py:194} INFO - Downloading h11-0.14.0-py3-none-any.whl (58 kB)
[2024-11-23T16:43:15.780+0000] {process_utils.py:194} INFO - Building wheels for collected packages: interpark
[2024-11-23T16:43:15.785+0000] {process_utils.py:194} INFO -   Building wheel for interpark (pyproject.toml): started
[2024-11-23T16:43:17.003+0000] {process_utils.py:194} INFO -   Building wheel for interpark (pyproject.toml): finished with status 'done'
[2024-11-23T16:43:17.496+0000] {process_utils.py:194} INFO -   Created wheel for interpark: filename=interpark-0.1.2-py3-none-any.whl size=17701 sha256=743abb620058afe141851c70c6483f96b4883cd1a9c5dcfca2603d271990d9d8
[2024-11-23T16:43:17.497+0000] {process_utils.py:194} INFO -   Stored in directory: /tmp/pip-ephem-wheel-cache-1p5yl9z2/wheels/3b/e3/3f/2198c53e48ab1c477124eda1522aad636d2590cc0e6349feda
[2024-11-23T16:43:17.500+0000] {process_utils.py:194} INFO - Successfully built interpark
[2024-11-23T16:43:17.554+0000] {process_utils.py:194} INFO - Installing collected packages: sortedcontainers, websocket-client, urllib3, typing_extensions, soupsieve, sniffio, pysocks, idna, h11, certifi, attrs, wsproto, outcome, beautifulsoup4, trio, trio-websocket, selenium, interpark
[2024-11-23T16:43:17.795+0000] {process_utils.py:194} INFO - Successfully installed attrs-24.2.0 beautifulsoup4-4.12.3 certifi-2024.8.30 h11-0.14.0 idna-3.10 interpark-0.1.2 outcome-1.3.0.post0 pysocks-1.7.1 selenium-4.26.1 sniffio-1.3.1 sortedcontainers-2.4.0 soupsieve-2.6 trio-0.27.0 trio-websocket-0.11.1 typing_extensions-4.12.2 urllib3-2.2.3 websocket-client-1.8.0 wsproto-1.2.0
[2024-11-23T16:43:18.172+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv6ip7ocnh/bin/python /tmp/venv-call0pzue72i/script.py /tmp/venv-call0pzue72i/script.in /tmp/venv-call0pzue72i/script.out /tmp/venv-call0pzue72i/string_args.txt /tmp/venv-call0pzue72i/termination.log
[2024-11-23T16:43:18.173+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T16:43:19.432+0000] {process_utils.py:194} INFO - The chromedriver version (114.0.5735.90) detected in PATH at /usr/local/bin/chromedriver might not be compatible with the detected chrome version (131.0.6778.85); currently, chromedriver 131.0.6778.85 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry
[2024-11-23T16:43:20.045+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2024-11-23T16:43:20.045+0000] {process_utils.py:194} INFO -   File "/tmp/venv-call0pzue72i/script.py", line 48, in <module>
[2024-11-23T16:43:20.046+0000] {process_utils.py:194} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-23T16:43:20.046+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:43:20.046+0000] {process_utils.py:194} INFO -   File "/tmp/venv-call0pzue72i/script.py", line 20, in get_data
[2024-11-23T16:43:20.046+0000] {process_utils.py:194} INFO -     get_data = extract_container_html()
[2024-11-23T16:43:20.046+0000] {process_utils.py:194} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:43:20.047+0000] {process_utils.py:194} INFO -   File "/tmp/venv6ip7ocnh/lib/python3.12/site-packages/interpark/test.py", line 19, in extract_container_html
[2024-11-23T16:43:20.047+0000] {process_utils.py:194} INFO -     driver = webdriver.Chrome(options=chrome_options)
[2024-11-23T16:43:20.047+0000] {process_utils.py:194} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:43:20.047+0000] {process_utils.py:194} INFO -   File "/tmp/venv6ip7ocnh/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
[2024-11-23T16:43:20.047+0000] {process_utils.py:194} INFO -     super().__init__(
[2024-11-23T16:43:20.047+0000] {process_utils.py:194} INFO -   File "/tmp/venv6ip7ocnh/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
[2024-11-23T16:43:20.048+0000] {process_utils.py:194} INFO -     super().__init__(command_executor=executor, options=options)
[2024-11-23T16:43:20.048+0000] {process_utils.py:194} INFO -   File "/tmp/venv6ip7ocnh/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
[2024-11-23T16:43:20.048+0000] {process_utils.py:194} INFO -     self.start_session(capabilities)
[2024-11-23T16:43:20.048+0000] {process_utils.py:194} INFO -   File "/tmp/venv6ip7ocnh/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
[2024-11-23T16:43:20.048+0000] {process_utils.py:194} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-11-23T16:43:20.049+0000] {process_utils.py:194} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:43:20.049+0000] {process_utils.py:194} INFO -   File "/tmp/venv6ip7ocnh/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
[2024-11-23T16:43:20.049+0000] {process_utils.py:194} INFO -     self.error_handler.check_response(response)
[2024-11-23T16:43:20.050+0000] {process_utils.py:194} INFO -   File "/tmp/venv6ip7ocnh/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2024-11-23T16:43:20.050+0000] {process_utils.py:194} INFO -     raise exception_class(message, screen, stacktrace)
[2024-11-23T16:43:20.050+0000] {process_utils.py:194} INFO - selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
[2024-11-23T16:43:20.050+0000] {process_utils.py:194} INFO -   (unknown error: DevToolsActivePort file doesn't exist)
[2024-11-23T16:43:20.050+0000] {process_utils.py:194} INFO -   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2024-11-23T16:43:20.051+0000] {process_utils.py:194} INFO - Stacktrace:
[2024-11-23T16:43:20.051+0000] {process_utils.py:194} INFO - #0 0x555a9917d4e3 <unknown>
[2024-11-23T16:43:20.051+0000] {process_utils.py:194} INFO - #1 0x555a98eacc76 <unknown>
[2024-11-23T16:43:20.051+0000] {process_utils.py:194} INFO - #2 0x555a98ed5d78 <unknown>
[2024-11-23T16:43:20.051+0000] {process_utils.py:194} INFO - #3 0x555a98ed2029 <unknown>
[2024-11-23T16:43:20.051+0000] {process_utils.py:194} INFO - #4 0x555a98f10ccc <unknown>
[2024-11-23T16:43:20.052+0000] {process_utils.py:194} INFO - #5 0x555a98f1047f <unknown>
[2024-11-23T16:43:20.052+0000] {process_utils.py:194} INFO - #6 0x555a98f07de3 <unknown>
[2024-11-23T16:43:20.052+0000] {process_utils.py:194} INFO - #7 0x555a98edd2dd <unknown>
[2024-11-23T16:43:20.052+0000] {process_utils.py:194} INFO - #8 0x555a98ede34e <unknown>
[2024-11-23T16:43:20.052+0000] {process_utils.py:194} INFO - #9 0x555a9913d3e4 <unknown>
[2024-11-23T16:43:20.052+0000] {process_utils.py:194} INFO - #10 0x555a991413d7 <unknown>
[2024-11-23T16:43:20.052+0000] {process_utils.py:194} INFO - #11 0x555a9914bb20 <unknown>
[2024-11-23T16:43:20.053+0000] {process_utils.py:194} INFO - #12 0x555a99142023 <unknown>
[2024-11-23T16:43:20.053+0000] {process_utils.py:194} INFO - #13 0x555a991101aa <unknown>
[2024-11-23T16:43:20.053+0000] {process_utils.py:194} INFO - #14 0x555a991666b8 <unknown>
[2024-11-23T16:43:20.053+0000] {process_utils.py:194} INFO - #15 0x555a99166847 <unknown>
[2024-11-23T16:43:20.053+0000] {process_utils.py:194} INFO - #16 0x555a99176243 <unknown>
[2024-11-23T16:43:20.053+0000] {process_utils.py:194} INFO - #17 0x7fa26997b144 <unknown>
[2024-11-23T16:43:20.053+0000] {process_utils.py:194} INFO - 
[2024-11-23T16:43:20.159+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x555a9917d4e3 <unknown>
#1 0x555a98eacc76 <unknown>
#2 0x555a98ed5d78 <unknown>
#3 0x555a98ed2029 <unknown>
#4 0x555a98f10ccc <unknown>
#5 0x555a98f1047f <unknown>
#6 0x555a98f07de3 <unknown>
#7 0x555a98edd2dd <unknown>
#8 0x555a98ede34e <unknown>
#9 0x555a9913d3e4 <unknown>
#10 0x555a991413d7 <unknown>
#11 0x555a9914bb20 <unknown>
#12 0x555a99142023 <unknown>
#13 0x555a991101aa <unknown>
#14 0x555a991666b8 <unknown>
#15 0x555a99166847 <unknown>
#16 0x555a99176243 <unknown>
#17 0x7fa26997b144 <unknown>

[2024-11-23T16:43:20.166+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=interpark_to_s3, task_id=extract, run_id=scheduled__2024-11-21T00:00:00+00:00, execution_date=20241121T000000, start_date=20241123T164258, end_date=20241123T164320
[2024-11-23T16:43:20.185+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T16:43:20.186+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 53 for task extract (Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x555a9917d4e3 <unknown>
#1 0x555a98eacc76 <unknown>
#2 0x555a98ed5d78 <unknown>
#3 0x555a98ed2029 <unknown>
#4 0x555a98f10ccc <unknown>
#5 0x555a98f1047f <unknown>
#6 0x555a98f07de3 <unknown>
#7 0x555a98edd2dd <unknown>
#8 0x555a98ede34e <unknown>
#9 0x555a9913d3e4 <unknown>
#10 0x555a991413d7 <unknown>
#11 0x555a9914bb20 <unknown>
#12 0x555a99142023 <unknown>
#13 0x555a991101aa <unknown>
#14 0x555a991666b8 <unknown>
#15 0x555a99166847 <unknown>
#16 0x555a99176243 <unknown>
#17 0x7fa26997b144 <unknown>
; 79)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x555a9917d4e3 <unknown>
#1 0x555a98eacc76 <unknown>
#2 0x555a98ed5d78 <unknown>
#3 0x555a98ed2029 <unknown>
#4 0x555a98f10ccc <unknown>
#5 0x555a98f1047f <unknown>
#6 0x555a98f07de3 <unknown>
#7 0x555a98edd2dd <unknown>
#8 0x555a98ede34e <unknown>
#9 0x555a9913d3e4 <unknown>
#10 0x555a991413d7 <unknown>
#11 0x555a9914bb20 <unknown>
#12 0x555a99142023 <unknown>
#13 0x555a991101aa <unknown>
#14 0x555a991666b8 <unknown>
#15 0x555a99166847 <unknown>
#16 0x555a99176243 <unknown>
#17 0x7fa26997b144 <unknown>

[2024-11-23T16:43:20.242+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T16:43:20.258+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T16:43:20.265+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
