[2024-11-23T16:02:57.912+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T16:02:57.933+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: interpark_to_s3.extract scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T16:02:57.942+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: interpark_to_s3.extract scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T16:02:57.943+0000] {taskinstance.py:2866} INFO - Starting attempt 13 of 14
[2024-11-23T16:02:57.961+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): extract> on 2024-11-22 00:00:00+00:00
[2024-11-23T16:02:57.968+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T16:02:57.969+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-11-23T16:02:57.970+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'interpark_to_s3', 'extract', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpyllgzytt']
[2024-11-23T16:02:57.971+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask extract
[2024-11-23T16:02:58.023+0000] {task_command.py:467} INFO - Running <TaskInstance: interpark_to_s3.extract scheduled__2024-11-22T00:00:00+00:00 [running]> on host e2f98aefb9d6
[2024-11-23T16:02:58.113+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='interpark_to_s3' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T16:02:58.113+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T16:02:58.143+0000] {baseoperator.py:416} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-11-23T16:02:58.145+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvxdst95xk --python=python
[2024-11-23T16:02:58.147+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T16:02:59.588+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 638ms
[2024-11-23T16:02:59.589+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvxdst95xk, clear=False, no_vcs_ignore=False, global=False)
[2024-11-23T16:02:59.589+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-23T16:02:59.589+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2024-11-23T16:02:59.589+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-23T16:02:59.648+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvxdst95xk/bin/pip install -r /tmp/venvxdst95xk/requirements.txt
[2024-11-23T16:02:59.649+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T16:03:01.548+0000] {process_utils.py:194} INFO - Collecting git+https://github.com/hahahellooo/interpark.git@0.3/new_crawling (from -r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:01.549+0000] {process_utils.py:194} INFO -   Cloning https://github.com/hahahellooo/interpark.git (to revision 0.3/new_crawling) to /tmp/pip-req-build-yt1a3zey
[2024-11-23T16:03:01.552+0000] {process_utils.py:194} INFO -   Running command git clone --filter=blob:none --quiet https://github.com/hahahellooo/interpark.git /tmp/pip-req-build-yt1a3zey
[2024-11-23T16:03:02.987+0000] {process_utils.py:194} INFO -   Running command git checkout -b 0.3/new_crawling --track origin/0.3/new_crawling
[2024-11-23T16:03:03.599+0000] {process_utils.py:194} INFO -   Switched to a new branch '0.3/new_crawling'
[2024-11-23T16:03:03.600+0000] {process_utils.py:194} INFO -   branch '0.3/new_crawling' set up to track 'origin/0.3/new_crawling'.
[2024-11-23T16:03:03.601+0000] {process_utils.py:194} INFO -   Resolved https://github.com/hahahellooo/interpark.git to commit d2ab75a632be9f578ac04be0e85d884befd10f87
[2024-11-23T16:03:03.607+0000] {process_utils.py:194} INFO -   Installing build dependencies: started
[2024-11-23T16:03:06.841+0000] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2024-11-23T16:03:06.842+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2024-11-23T16:03:04.894+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'done'
[2024-11-23T16:03:04.896+0000] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): started
[2024-11-23T16:03:05.852+0000] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): finished with status 'done'
[2024-11-23T16:03:06.012+0000] {process_utils.py:194} INFO - Collecting selenium>=4.26.1 (from interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.070+0000] {process_utils.py:194} INFO -   Downloading selenium-4.26.1-py3-none-any.whl.metadata (7.1 kB)
[2024-11-23T16:03:06.144+0000] {process_utils.py:194} INFO - Collecting beautifulsoup4>=4.12.3 (from interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.152+0000] {process_utils.py:194} INFO -   Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
[2024-11-23T16:03:06.229+0000] {process_utils.py:194} INFO - Collecting soupsieve>1.2 (from beautifulsoup4>=4.12.3->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.237+0000] {process_utils.py:194} INFO -   Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
[2024-11-23T16:03:06.373+0000] {process_utils.py:194} INFO - Collecting urllib3<3,>=1.26 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.382+0000] {process_utils.py:194} INFO -   Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
[2024-11-23T16:03:06.465+0000] {process_utils.py:194} INFO - Collecting trio~=0.17 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.473+0000] {process_utils.py:194} INFO -   Downloading trio-0.27.0-py3-none-any.whl.metadata (8.6 kB)
[2024-11-23T16:03:06.551+0000] {process_utils.py:194} INFO - Collecting trio-websocket~=0.9 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.561+0000] {process_utils.py:194} INFO -   Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
[2024-11-23T16:03:06.658+0000] {process_utils.py:194} INFO - Collecting certifi>=2021.10.8 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.666+0000] {process_utils.py:194} INFO -   Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
[2024-11-23T16:03:06.746+0000] {process_utils.py:194} INFO - Collecting typing_extensions~=4.9 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.755+0000] {process_utils.py:194} INFO -   Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
[2024-11-23T16:03:06.839+0000] {process_utils.py:194} INFO - Collecting websocket-client~=1.8 (from selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.849+0000] {process_utils.py:194} INFO -   Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
[2024-11-23T16:03:06.939+0000] {process_utils.py:194} INFO - Collecting attrs>=23.2.0 (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:06.947+0000] {process_utils.py:194} INFO -   Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
[2024-11-23T16:03:07.056+0000] {process_utils.py:194} INFO - Collecting sortedcontainers (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:07.066+0000] {process_utils.py:194} INFO -   Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
[2024-11-23T16:03:07.163+0000] {process_utils.py:194} INFO - Collecting idna (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:07.172+0000] {process_utils.py:194} INFO -   Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
[2024-11-23T16:03:07.256+0000] {process_utils.py:194} INFO - Collecting outcome (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:07.265+0000] {process_utils.py:194} INFO -   Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
[2024-11-23T16:03:07.339+0000] {process_utils.py:194} INFO - Collecting sniffio>=1.3.0 (from trio~=0.17->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:07.348+0000] {process_utils.py:194} INFO -   Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
[2024-11-23T16:03:07.421+0000] {process_utils.py:194} INFO - Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:07.435+0000] {process_utils.py:194} INFO -   Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
[2024-11-23T16:03:07.514+0000] {process_utils.py:194} INFO - Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:07.523+0000] {process_utils.py:194} INFO -   Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
[2024-11-23T16:03:07.599+0000] {process_utils.py:194} INFO - Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium>=4.26.1->interpark==0.1.2->-r /tmp/venvxdst95xk/requirements.txt (line 1))
[2024-11-23T16:03:07.607+0000] {process_utils.py:194} INFO -   Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
[2024-11-23T16:03:07.656+0000] {process_utils.py:194} INFO - Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
[2024-11-23T16:03:07.711+0000] {process_utils.py:194} INFO - Downloading selenium-4.26.1-py3-none-any.whl (9.7 MB)
[2024-11-23T16:03:09.407+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 5.7 MB/s eta 0:00:00
[2024-11-23T16:03:09.420+0000] {process_utils.py:194} INFO - Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
[2024-11-23T16:03:09.499+0000] {process_utils.py:194} INFO - Downloading soupsieve-2.6-py3-none-any.whl (36 kB)
[2024-11-23T16:03:09.547+0000] {process_utils.py:194} INFO - Downloading trio-0.27.0-py3-none-any.whl (481 kB)
[2024-11-23T16:03:09.688+0000] {process_utils.py:194} INFO - Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
[2024-11-23T16:03:09.821+0000] {process_utils.py:194} INFO - Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
[2024-11-23T16:03:09.875+0000] {process_utils.py:194} INFO - Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
[2024-11-23T16:03:09.931+0000] {process_utils.py:194} INFO - Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
[2024-11-23T16:03:09.984+0000] {process_utils.py:194} INFO - Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
[2024-11-23T16:03:10.034+0000] {process_utils.py:194} INFO - Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
[2024-11-23T16:03:10.076+0000] {process_utils.py:194} INFO - Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
[2024-11-23T16:03:10.124+0000] {process_utils.py:194} INFO - Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
[2024-11-23T16:03:10.160+0000] {process_utils.py:194} INFO - Downloading idna-3.10-py3-none-any.whl (70 kB)
[2024-11-23T16:03:10.208+0000] {process_utils.py:194} INFO - Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
[2024-11-23T16:03:10.266+0000] {process_utils.py:194} INFO - Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
[2024-11-23T16:03:10.307+0000] {process_utils.py:194} INFO - Downloading h11-0.14.0-py3-none-any.whl (58 kB)
[2024-11-23T16:03:10.402+0000] {process_utils.py:194} INFO - Building wheels for collected packages: interpark
[2024-11-23T16:03:10.407+0000] {process_utils.py:194} INFO -   Building wheel for interpark (pyproject.toml): started
[2024-11-23T16:03:11.501+0000] {process_utils.py:194} INFO -   Building wheel for interpark (pyproject.toml): finished with status 'done'
[2024-11-23T16:03:11.502+0000] {process_utils.py:194} INFO -   Created wheel for interpark: filename=interpark-0.1.2-py3-none-any.whl size=17701 sha256=ca71539c381ed0a9d466e767b2c9930596d71b9aba2863b1e9872e966f00253d
[2024-11-23T16:03:11.502+0000] {process_utils.py:194} INFO -   Stored in directory: /tmp/pip-ephem-wheel-cache-3uo7vhxl/wheels/3b/e3/3f/2198c53e48ab1c477124eda1522aad636d2590cc0e6349feda
[2024-11-23T16:03:11.505+0000] {process_utils.py:194} INFO - Successfully built interpark
[2024-11-23T16:03:11.553+0000] {process_utils.py:194} INFO - Installing collected packages: sortedcontainers, websocket-client, urllib3, typing_extensions, soupsieve, sniffio, pysocks, idna, h11, certifi, attrs, wsproto, outcome, beautifulsoup4, trio, trio-websocket, selenium, interpark
[2024-11-23T16:03:16.757+0000] {process_utils.py:194} INFO - Successfully installed attrs-24.2.0 beautifulsoup4-4.12.3 certifi-2024.8.30 h11-0.14.0 idna-3.10 interpark-0.1.2 outcome-1.3.0.post0 pysocks-1.7.1 selenium-4.26.1 sniffio-1.3.1 sortedcontainers-2.4.0 soupsieve-2.6 trio-0.27.0 trio-websocket-0.11.1 typing_extensions-4.12.2 urllib3-2.2.3 websocket-client-1.8.0 wsproto-1.2.0
[2024-11-23T16:03:17.186+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvxdst95xk/bin/python /tmp/venv-callwtv1roid/script.py /tmp/venv-callwtv1roid/script.in /tmp/venv-callwtv1roid/script.out /tmp/venv-callwtv1roid/string_args.txt /tmp/venv-callwtv1roid/termination.log
[2024-11-23T16:03:17.187+0000] {process_utils.py:190} INFO - Output:
[2024-11-23T16:03:18.309+0000] {process_utils.py:194} INFO - The chromedriver version (114.0.5735.90) detected in PATH at /usr/local/bin/chromedriver might not be compatible with the detected chrome version (131.0.6778.85); currently, chromedriver 131.0.6778.85 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry
[2024-11-23T16:03:18.520+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2024-11-23T16:03:18.521+0000] {process_utils.py:194} INFO -   File "/tmp/venv-callwtv1roid/script.py", line 48, in <module>
[2024-11-23T16:03:18.521+0000] {process_utils.py:194} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-23T16:03:18.521+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:03:18.521+0000] {process_utils.py:194} INFO -   File "/tmp/venv-callwtv1roid/script.py", line 20, in get_data
[2024-11-23T16:03:18.522+0000] {process_utils.py:194} INFO -     get_data = extract_container_html()
[2024-11-23T16:03:18.522+0000] {process_utils.py:194} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:03:18.522+0000] {process_utils.py:194} INFO -   File "/tmp/venvxdst95xk/lib/python3.12/site-packages/interpark/test.py", line 19, in extract_container_html
[2024-11-23T16:03:18.522+0000] {process_utils.py:194} INFO -     driver = webdriver.Chrome(options=chrome_options)
[2024-11-23T16:03:18.522+0000] {process_utils.py:194} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:03:18.523+0000] {process_utils.py:194} INFO -   File "/tmp/venvxdst95xk/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
[2024-11-23T16:03:18.523+0000] {process_utils.py:194} INFO -     super().__init__(
[2024-11-23T16:03:18.523+0000] {process_utils.py:194} INFO -   File "/tmp/venvxdst95xk/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
[2024-11-23T16:03:18.523+0000] {process_utils.py:194} INFO -     super().__init__(command_executor=executor, options=options)
[2024-11-23T16:03:18.524+0000] {process_utils.py:194} INFO -   File "/tmp/venvxdst95xk/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
[2024-11-23T16:03:18.524+0000] {process_utils.py:194} INFO -     self.start_session(capabilities)
[2024-11-23T16:03:18.524+0000] {process_utils.py:194} INFO -   File "/tmp/venvxdst95xk/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
[2024-11-23T16:03:18.524+0000] {process_utils.py:194} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-11-23T16:03:18.525+0000] {process_utils.py:194} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-23T16:03:18.526+0000] {process_utils.py:194} INFO -   File "/tmp/venvxdst95xk/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
[2024-11-23T16:03:18.526+0000] {process_utils.py:194} INFO -     self.error_handler.check_response(response)
[2024-11-23T16:03:18.527+0000] {process_utils.py:194} INFO -   File "/tmp/venvxdst95xk/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2024-11-23T16:03:18.527+0000] {process_utils.py:194} INFO -     raise exception_class(message, screen, stacktrace)
[2024-11-23T16:03:18.527+0000] {process_utils.py:194} INFO - selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
[2024-11-23T16:03:18.527+0000] {process_utils.py:194} INFO -   (unknown error: DevToolsActivePort file doesn't exist)
[2024-11-23T16:03:18.528+0000] {process_utils.py:194} INFO -   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2024-11-23T16:03:18.528+0000] {process_utils.py:194} INFO - Stacktrace:
[2024-11-23T16:03:18.528+0000] {process_utils.py:194} INFO - #0 0x56218af7e4e3 <unknown>
[2024-11-23T16:03:18.528+0000] {process_utils.py:194} INFO - #1 0x56218acadc76 <unknown>
[2024-11-23T16:03:18.529+0000] {process_utils.py:194} INFO - #2 0x56218acd6d78 <unknown>
[2024-11-23T16:03:18.529+0000] {process_utils.py:194} INFO - #3 0x56218acd3029 <unknown>
[2024-11-23T16:03:18.529+0000] {process_utils.py:194} INFO - #4 0x56218ad11ccc <unknown>
[2024-11-23T16:03:18.529+0000] {process_utils.py:194} INFO - #5 0x56218ad1147f <unknown>
[2024-11-23T16:03:18.530+0000] {process_utils.py:194} INFO - #6 0x56218ad08de3 <unknown>
[2024-11-23T16:03:18.530+0000] {process_utils.py:194} INFO - #7 0x56218acde2dd <unknown>
[2024-11-23T16:03:18.530+0000] {process_utils.py:194} INFO - #8 0x56218acdf34e <unknown>
[2024-11-23T16:03:18.530+0000] {process_utils.py:194} INFO - #9 0x56218af3e3e4 <unknown>
[2024-11-23T16:03:18.530+0000] {process_utils.py:194} INFO - #10 0x56218af423d7 <unknown>
[2024-11-23T16:03:18.531+0000] {process_utils.py:194} INFO - #11 0x56218af4cb20 <unknown>
[2024-11-23T16:03:18.531+0000] {process_utils.py:194} INFO - #12 0x56218af43023 <unknown>
[2024-11-23T16:03:18.531+0000] {process_utils.py:194} INFO - #13 0x56218af111aa <unknown>
[2024-11-23T16:03:18.531+0000] {process_utils.py:194} INFO - #14 0x56218af676b8 <unknown>
[2024-11-23T16:03:18.531+0000] {process_utils.py:194} INFO - #15 0x56218af67847 <unknown>
[2024-11-23T16:03:18.531+0000] {process_utils.py:194} INFO - #16 0x56218af77243 <unknown>
[2024-11-23T16:03:18.532+0000] {process_utils.py:194} INFO - #17 0x7f120088a144 <unknown>
[2024-11-23T16:03:18.532+0000] {process_utils.py:194} INFO - 
[2024-11-23T16:03:18.652+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56218af7e4e3 <unknown>
#1 0x56218acadc76 <unknown>
#2 0x56218acd6d78 <unknown>
#3 0x56218acd3029 <unknown>
#4 0x56218ad11ccc <unknown>
#5 0x56218ad1147f <unknown>
#6 0x56218ad08de3 <unknown>
#7 0x56218acde2dd <unknown>
#8 0x56218acdf34e <unknown>
#9 0x56218af3e3e4 <unknown>
#10 0x56218af423d7 <unknown>
#11 0x56218af4cb20 <unknown>
#12 0x56218af43023 <unknown>
#13 0x56218af111aa <unknown>
#14 0x56218af676b8 <unknown>
#15 0x56218af67847 <unknown>
#16 0x56218af77243 <unknown>
#17 0x7f120088a144 <unknown>

[2024-11-23T16:03:18.662+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=interpark_to_s3, task_id=extract, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T160257, end_date=20241123T160318
[2024-11-23T16:03:18.687+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T16:03:18.687+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 48 for task extract (Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56218af7e4e3 <unknown>
#1 0x56218acadc76 <unknown>
#2 0x56218acd6d78 <unknown>
#3 0x56218acd3029 <unknown>
#4 0x56218ad11ccc <unknown>
#5 0x56218ad1147f <unknown>
#6 0x56218ad08de3 <unknown>
#7 0x56218acde2dd <unknown>
#8 0x56218acdf34e <unknown>
#9 0x56218af3e3e4 <unknown>
#10 0x56218af423d7 <unknown>
#11 0x56218af4cb20 <unknown>
#12 0x56218af43023 <unknown>
#13 0x56218af111aa <unknown>
#14 0x56218af676b8 <unknown>
#15 0x56218af67847 <unknown>
#16 0x56218af77243 <unknown>
#17 0x7f120088a144 <unknown>
; 78)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56218af7e4e3 <unknown>
#1 0x56218acadc76 <unknown>
#2 0x56218acd6d78 <unknown>
#3 0x56218acd3029 <unknown>
#4 0x56218ad11ccc <unknown>
#5 0x56218ad1147f <unknown>
#6 0x56218ad08de3 <unknown>
#7 0x56218acde2dd <unknown>
#8 0x56218acdf34e <unknown>
#9 0x56218af3e3e4 <unknown>
#10 0x56218af423d7 <unknown>
#11 0x56218af4cb20 <unknown>
#12 0x56218af43023 <unknown>
#13 0x56218af111aa <unknown>
#14 0x56218af676b8 <unknown>
#15 0x56218af67847 <unknown>
#16 0x56218af77243 <unknown>
#17 0x7f120088a144 <unknown>

[2024-11-23T16:03:18.711+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T16:03:18.736+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T16:03:18.740+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
